apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'
  
  workflow_dispatch:
    inputs:
      inputs_a:
        required: false
        default: thisisatest
      inputs_b:
        required: true
        type: number


jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
